### ISSUE TITLE
Is importProcessor not designed for internal use?

### ISSUE THREAD

**Issue by petitroto** [jonathan-casarrubias/loopback-import-mixin#1]
Thank you for sharing your great product!

Is importProcessor not designed for internal use?
I want to use this mix-in for app initialization.
So, It's better not with REST API but with code.

**Comment by jonathan-casarrubias** [comment]
Hello @petitroto 

importProcessor is a forked operation that will run the import process in the background so we don't keep users waiting for the process to finish, what you want to do is to call the import method created by the mixing if you don't define any.

So for example, if you don't define a method name you will be able to use this programatically by invoking `YourModel.import(req, next)` and then this method will fork a process and run the importProcessor in background.

By default the mixing uses the import name, but you can set any name you want because you may need to do multiple imports to same model with different configurations, so for example:

``` js
{
    "Import": [
        {
            "method": "yourImportMethodName1",
            "endpoint": "/yourendpoint1",
            "map": {
                // Configurations 1
            }
        },
        {
            "method": "yourImportMethodName2",
            "endpoint": "/yourendpoint2",
            "map": {
                // Configurations 2
            }
        }
    ]
}
```

So after the configuration above you should be able to invoke

`YourModel.yourImportMethodName1(req, next)` or `YourModel.yourImportMethodName2(req, next)` from a boot script, or a hook, etc.. So you are able to use this functionality through JS or REST.

Cheers!
Jon
