### ISSUE TITLE
Is HasAndBelongsToMany relation not supported?

### ISSUE THREAD

**Issue by petitroto** [jonathan-casarrubias/loopback-import-mixin#2]
To import many-to-many relationships,
Is 'through' model required? (hasManyThrough relation)

**Comment by jonathan-casarrubias** [comment]
Hello @petitroto thanks your interest in this mixin.

The mixin right now (1.0.6) supports 2 types of relational operations

 1.- Link
 2.- Create

So at this moment Yes it does support many-to-many operations on both (link and create)

# Example

``` js
{
    "Import": {
        "pk": "cvsField", // So we don't duplicate root instance
        "map": {
            // Your root instance properties map...
        },
        "relations": {
            // This links your new root model with existing many to many models where the statement matches
            "manyToManyRelationLink": {
                "type": "link",
                "where": { "relatedModelProperty": "cvsKeyField" }
            }
           // This creates many to many instances  and relates with your root model
            "manyToManyRelationCreate": {
                "type": "create",
                "map": {
                    // Same type properties map configuration as root, but now for
                    //  the related model instances to be created
                }
            }
        }
    }
}
```

At this moment you don't need to define the intermediate model (through) since its is not necessary, at the end it does something like

`Model.yourManyToManyRelation.add()` when you use the link configuration and  `Model.yourManyToManyRelation.create(map)` when you use create

I hope this help to you.

Cheers

Jon
